# deploy.yml

name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - master
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Set Custom Secrets
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} STRIPE_PRICE_ID=${{ secrets.STRIPE_PRICE_ID }}
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} SITE_URL=${{ secrets.SITE_URL }}
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} CUSTOM_SUPABASE_SERVICE_ROLE_KEY=${{ secrets.CUSTOM_SUPABASE_SERVICE_ROLE_KEY }}

      - name: Deploy Supabase Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy start-subscription --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
          supabase functions deploy create-checkout-link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
          supabase functions deploy stripe-webhook --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt