# deploy.yml

name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - master
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Set All Secrets
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          # Segredos do Mercado Pago
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} MERCADO_PAGO_ACCESS_TOKEN=${{ secrets.MERCADO_PAGO_ACCESS_TOKEN }}
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} MERCADO_PAGO_PLAN_ID=${{ secrets.MERCADO_PAGO_PLAN_ID }}
          
          # Segredos do Supabase (CRUCIAIS para a função rodar)
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} SITE_URL=${{ secrets.SITE_URL }}
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}

      - name: Deploy Supabase Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy start-subscription --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
          supabase functions deploy mercado-pago-webhook --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
          supabase functions deploy create-checkout-link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt