# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Deploy Supabase Function

# Gatilho (trigger): Define quando o workflow deve rodar
on:
  push:
    branches:
      # Roda apenas para pushes feitos na branch 'master'
      - master
    paths:
      # Roda apenas se houver qualquer alteração dentro da pasta de functions
      - 'supabase/functions/**'

# Tarefas (jobs) que serão executadas
jobs:
  deploy:
    # Define o tipo de máquina virtual que executará o job
    runs-on: ubuntu-latest

    # Passos (steps) a serem seguidos dentro do job
    steps:
      # Passo 1: Baixa (clona) o seu código do repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Instala e configura a ferramenta de linha de comando (CLI) do Supabase
      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Passo 3: Executa o comando para fazer o deploy das suas functions para o Supabase
      - name: Deploy Supabase Edge Functions
        run: |
          # Deploy da função que inicia a assinatura
          supabase functions deploy start-subscription --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
          
          # Deploy da função de webhook que recebe a confirmação de pagamento
          supabase functions deploy mercado-pago-webhook --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
        env:
          # Segredos do Supabase - Necessários para autenticar o comando de deploy
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          
          # Segredos do Projeto - Serão injetados como variáveis de ambiente nas suas functions
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SITE_URL: ${{ secrets.SITE_URL }}
          MERCADO_PAGO_ACCESS_TOKEN: ${{ secrets.MERCADO_PAGO_ACCESS_TOKEN }}
          MERCADO_PAGO_PLAN_ID: ${{ secrets.MERCADO_PAGO_PLAN_ID }}