name: Deploy Supabase Function

on:
  push:
    branches:
      # Configurado para a sua branch principal
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Deploy to Supabase
        uses: supabase/actions-workflow@v1.0.3
        with:
          access-token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          args: functions deploy --project-id ${{ secrets.SUPABASE_PROJECT_ID }}