name: Deploy Supabase Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Supabase CLI
        uses: supabase/cli@v1
        with:
          version: latest

      - name: Deploy Supabase Edge Function
        run: supabase functions deploy --project-id ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}