name: Deploy Supabase Function

on:
  push:
    branches:
      # Configurado para a sua branch principal
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Deploy to Supabase
        # Este é o nome CORRETO da action oficial do Supabase
        uses: supabase/github-action@v1.0.0
        with:
          access-token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          args: 'functions deploy --project-id ${{ secrets.SUPABASE_PROJECT_ID }}'
